development:
  adapter: postgresql
  database: grainbill_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: grainbill_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: grainbill_prod
  pool: 5
  timeout: 5000
